apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
      - name: auth-service
        image: <auth-service-image>
        ports:
        - containerPort: 4005
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "prod"
