apiVersion: v1
kind: Service
metadata:
  name: billing-service
spec:
  selector:
    app: billing-service
  ports:
  - port: 4001
    targetPort: 4001
  - port: 9001
    targetPort: 9001
  type: ClusterIP
